'use strict';

// Finds and parses meowcoin.conf so we can pull RPC credentials without
// asking the user to copy/paste them. Falls back to the .cookie file if
// the conf doesn't set rpcuser/rpcpassword.

const fs = require('fs');
const path = require('path');
const os = require('os');

const DEFAULT_MAINNET_PORT = 9766;
const DEFAULT_TESTNET_PORT = 19766;

function candidateDataDirs() {
    const home = os.homedir();
    const dirs = [];

    if (process.platform === 'win32') {
        const appdata = process.env.APPDATA || path.join(home, 'AppData', 'Roaming');
        dirs.push(path.join(appdata, 'Meowcoin'));
    }
    else if (process.platform === 'darwin') {
        dirs.push(path.join(home, 'Library', 'Application Support', 'Meowcoin'));
    }
    else {
        dirs.push(path.join(home, '.meowcoin'));
    }

    return dirs;
}

function findConfFile() {
    for (const dir of candidateDataDirs()) {
        const p = path.join(dir, 'meowcoin.conf');
        if (fs.existsSync(p))
            return { confPath: p, dataDir: dir };
    }
    return null;
}

// Parse a bitcoin-core-style key=value config file. Strips comments (#),
// trims whitespace, ignores [section] headers (we don't need them here).
function parseConf(text) {
    const out = {};
    for (const raw of text.split(/\r?\n/)) {
        const line = raw.replace(/#.*$/, '').trim();
        if (!line || line.startsWith('[')) continue;
        const eq = line.indexOf('=');
        if (eq < 0) continue;
        const key = line.slice(0, eq).trim().toLowerCase();
        const val = line.slice(eq + 1).trim();
        out[key] = val;
    }
    return out;
}

// Read a .cookie file (auto-generated by Meowcoin Core when no rpcuser is set).
// Format: __cookie__:<random-password>
function tryCookie(dataDir, isTestnet) {
    const cookiePath = isTestnet
        ? path.join(dataDir, 'testnet4', '.cookie')
        : path.join(dataDir, '.cookie');
    if (!fs.existsSync(cookiePath)) return null;
    try {
        const txt = fs.readFileSync(cookiePath, 'utf8').trim();
        const colon = txt.indexOf(':');
        if (colon < 0) return null;
        return {
            user: txt.slice(0, colon),
            password: txt.slice(colon + 1),
            source: cookiePath,
        };
    } catch (err) {
        return null;
    }
}

// Returns { host, port, user, password, source, isTestnet, dataDir, confPath }
// or null if nothing found.
function autoDiscoverRpc() {
    const found = findConfFile();
    if (!found) return null;

    const text = fs.readFileSync(found.confPath, 'utf8');
    const conf = parseConf(text);
    const isTestnet = conf.testnet === '1' || conf.testnet4 === '1';

    const host = conf.rpcconnect || conf.rpcbind || '127.0.0.1';
    const port = parseInt(conf.rpcport, 10)
        || (isTestnet ? DEFAULT_TESTNET_PORT : DEFAULT_MAINNET_PORT);

    if (conf.rpcuser && conf.rpcpassword) {
        return {
            host,
            port,
            user: conf.rpcuser,
            password: conf.rpcpassword,
            source: found.confPath,
            isTestnet,
            dataDir: found.dataDir,
            confPath: found.confPath,
        };
    }

    // No rpcuser/rpcpassword — fall back to the cookie file.
    const cookie = tryCookie(found.dataDir, isTestnet);
    if (cookie) {
        return {
            host,
            port,
            user: cookie.user,
            password: cookie.password,
            source: cookie.source,
            isTestnet,
            dataDir: found.dataDir,
            confPath: found.confPath,
        };
    }

    return {
        host,
        port,
        user: null,
        password: null,
        source: null,
        isTestnet,
        dataDir: found.dataDir,
        confPath: found.confPath,
    };
}

module.exports = {
    DEFAULT_MAINNET_PORT,
    DEFAULT_TESTNET_PORT,
    candidateDataDirs,
    findConfFile,
    parseConf,
    autoDiscoverRpc,
};
